In [3]:
import cv2
import numpy as np

In [4]:
kernel_size = 5

In [6]:
kernel = np.ones((kernel_size, kernel_size), np.uint8)
kernel

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [7]:
gauss = cv2.getGaussianKernel(kernel_size, 0)
gauss

array([[0.0625],
       [0.25  ],
       [0.375 ],
       [0.25  ],
       [0.0625]])

In [8]:
gauss.transpose(1, 0)

array([[0.0625, 0.25  , 0.375 , 0.25  , 0.0625]])

In [9]:
gauss * gauss.transpose(1, 0)

array([[0.00390625, 0.015625  , 0.0234375 , 0.015625  , 0.00390625],
       [0.015625  , 0.0625    , 0.09375   , 0.0625    , 0.015625  ],
       [0.0234375 , 0.09375   , 0.140625  , 0.09375   , 0.0234375 ],
       [0.015625  , 0.0625    , 0.09375   , 0.0625    , 0.015625  ],
       [0.00390625, 0.015625  , 0.0234375 , 0.015625  , 0.00390625]])